const STATUS = {
  SUCCESS: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};

const METHODS = {
  ENTERING_TO: "ENTERING_TO",
  BUSINESS_METHOD: "BUSINESS_METHOD",
  SERVICE_METHOD: "SERVICE_METHOD",
  CONTROLLER_METHOD: "CONTROLLER_METHOD",
  VERIFY_TOKEN: "VERIFY_TOKEN",

  MODULES: {
    USER: {
      CREATE_USER: "CREATE_USER",
      FIND_USER: "FIND_USER",
      GET_USER: "GET_USER",
      UPDATE_USER: "UPDATE_USER",
      DELETE_USER: "DELETE_USER",
      GENERATE_LOGIN_TOKEN: "GENERATE_LOGIN_TOKEN",
    },
    PROVIDER: {
      GENERATE_LOGIN_TOKEN: "GENERATE_LOGIN_TOKEN",
      CREATE_PROVIDER: "CREATE_PROVIDER",
      FIND_PROVIDER: "FIND_PROVIDER",
    },
    EMAIL: {
      VERIFY_USER_EMAIL: "VERIFY_USER_EMAIL",
      VERIFY_PROVIDER_EMAIL: "VERIFY_PROVIDER_EMAIL",
    },
  },
};

module.exports = {
  METHODS,
  STATUS,
};
