const STATUS = {
  SUCCESS: 200,
  NOT_FOUND: 404,
  BAD_REQUEST: 400,
};

const METHODS = {
  ENTERING_TO: "ENTERING_TO",
  BUSINESS_METHOD: "BUSINESS_METHOD",
  SERVICE_METHOD: "SERVICE_METHOD",
  CONTROLLER_METHOD: "CONTROLLER_METHOD",

  MODULES: {
    USER: {
      CREATE_USER: "CREATE_USER",
      FIND_USER: "FIND_USER",
      GET_USER: "GET_USER",
      UPDATE_USER: "UPDATE_USER",
      DELETE_USER: "DELETE_USER",
    },
  },
};

module.exports = {
  METHODS,
  STATUS,
};
